# Generated by Django 4.1.3 on 2023-01-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
    ]
