# Generated by Django 4.1.3 on 2022-11-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_branch_access',
            name='write_access',
        ),
        migrations.RemoveField(
            model_name='user_branch_access',
            name='write_access',
        ),
    ]
