# Generated by Django 4.1.3 on 2022-12-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch_management', '0001_initial'),
        ('access_management', '0002_remove_group_branch_access_write_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='branch_management.branch'),
        ),
        migrations.DeleteModel(
            name='Group_branch_access',
        ),
    ]
