# Generated by Django 4.1.3 on 2023-01-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['last_name']},
        ),
    ]
