# Generated by Django 4.1.3 on 2022-12-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('known_locations_management', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('zip_code', 'city', 'country'), name='unique_location'),
        ),
    ]
