# Generated by Django 4.1.3 on 2023-01-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportations',
            options={'ordering': ['-departure_time']},
        ),
    ]
